language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
        - python: 3.6
          dist: xenial
        - python: 3.5
          dist: trusty
        - python: 3.4
          dist: trusty
        - python: 2.7
          dist: xenial
        - python: pypy3.5
          dist: xenial

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install --no-root

script:
  - pip install .
  - python -m pytest tests
  - python -m flake8 src
