language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
        - python: 3.6
          dist: xenial
        - python: 3.5
          dist: trusty
        - python: 3.4
          dist: trusty
        - python: 2.7
          dist: xenial
        - python: pypy3.5
          dist: xenial

install:
  - python -m pip install pipenv
  - python -m pipenv install

script:
  - python setup.py build
  - python setup.py install
  - python -m pytest tests
